### ISSUE TITLE
File associations broken on Electron <8

### ISSUE THREAD

**Issue by bendemboski** [tympanix/electron-regedit#3]
[this](https://github.com/tympanix/electron-regedit/commit/9ae0dc3d3a162565b5671cff23f502b86fb66a9a#diff-0647726deeb1a588ca99ed7f703e8535R15) was a breaking change for anyone running Electron <8 since `app.name` is undefined.

The result was that after updating my application to use the latest `electron-regedit` (a minor version bump that should not have breaking changes), the next time `Regedit.installAll()` runs, it leaves my old file associations in place and creates a new set of associations using the application name `undefined`, so:

1. When right-clicking on one of my files, I get two open with... options, one with my actual app name (the old entries) and one with `undefined`
2. When double-clicking on one of my files, it opens with the old version of the app (still on the system because of how squirrel works, and apparently the default application for my file type) rather than the updated version

I think this that change should be rolled back and re-released as a new major version, or should have some compatibility code added to detect whether to use `app.name` or `app.getName()`.

**Comment by tympanix** [comment]
I am sorry for this inconvenience. In hindsight, this should have been a major release. Instead of relying on some custom patching, I think we should roll back and re-release as a major version.

I don't think npm allows overwriting or re-publishing artifacts. However, we could release a minor version with the roll back and then a major version with the v8 compatibility.

Regarding the multiple entries in the context menu, that will most likely be unaffected by the roll back which would require some cleanup procedure. Whether we should supply this alongside `electron-regedit` is up for debate.

**Comment by bendemboski** [comment]
Cool, yeah, that all makes sense. You're right that cleaning up the entries takes some extra work -- I just added a bit of code to import `winreg` and clean them up manually -- I wouldn't think code like that belongs in `electron-regedit`, at least not unless it were in the context of some more broadly applicable capabilities.

Thanks for the quick response (and thanks for the library, it's been working really well for me overall)!

**Comment by tympanix** [comment]
No problem, glad you found it useful 👍 

I've made a deprecation notice on npm for version 1.1.0 and published a new 1.1.1 release with a roll-back. Also a new 2.0.0 release which supports electron >=8 (now also indicated in the `package.json` file).
